
server:
   port: 8081
   
spring:
  profiles:
    active: dev
---

spring:
  profiles: dev
  datasource:
    username: root
    password: root@123
    url: jdbc://mysql://localhost:3306/inventory_dev_db
    driver-class-name: com.mysql.jdbc.Driver
    
---  
spring:
  profiles: test
  datasource:
    username: root
    password: root@123
    url: jdbc://mysql://localhost:3306/inventory_test_db
    driver-class-name: com.mysql.jdbc.Driver
    
    
---
spring:
  profiles: uat
  datasource:
    username: root
    password: root@123
    url: jdbc://mysql://localhost:3306/inventory_uat_db
    driver-class-name: com.mysql.jdbc.Driver
    
    
---
spring:
  profiles: prod
  datasource:
    username: root
    password: root@123
    url: jdbc://mysql://localhost:3306/inventory_prod_db
    driver-class-name: com.mysql.jdbc.Driver
 
    
   
    
       